from __future__ import annotations

import json
import posixpath
import re
from collections.abc import Mapping, Sequence
from pathlib import PurePosixPath
from typing import Any

from .artifacts import checked_relative_path


_CARGO_NAME = re.compile(r"[A-Za-z][A-Za-z0-9_-]{0,63}\Z")
_RUST_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
_EDITIONS = {"2015", "2018", "2021", "2024"}
_LIB_CRATE_TYPES = {"lib", "rlib", "staticlib"}


def package_root(package_id: str) -> str:
    if (
        not isinstance(package_id, str)
        or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", package_id)
        or package_id in {".", ".."}
    ):
        raise ValueError("rust_project_cargo_v3_package_id_unrepresentable")
    return f"packages/{package_id}"


def checked_output_path(value: Any) -> str:
    try:
        path = checked_relative_path(value)
    except (TypeError, ValueError) as error:
        raise ValueError("rust_project_cargo_v3_path_invalid") from error
    if any(ord(char) < 32 for char in path):
        raise ValueError("rust_project_cargo_v3_path_invalid")
    return path


def module_name(module: Mapping[str, Any]) -> str:
    explicit = module.get("module_name", module.get("identifier"))
    if explicit is not None:
        if not isinstance(explicit, str) or not _RUST_IDENT.fullmatch(explicit):
            raise ValueError("rust_project_cargo_v3_module_name_unrepresentable")
        return explicit
    identity = module.get("module_id")
    if not isinstance(identity, str) or not identity:
        raise ValueError("rust_project_cargo_v3_module_name_unrepresentable")
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", identity)
    return f"c2rust_{normalized}"


def render_workspace_toml(
    workspace: Mapping[str, Any], packages: Mapping[str, Mapping[str, Any]],
    ir_sha256: str, projection_sha256: str,
) -> bytes:
    members = list(workspace["member_paths"])
    defaults = list(workspace["default_member_paths"])
    if members != sorted(package_root(package_id) for package_id in packages):
        raise ValueError("rust_project_cargo_v3_workspace_members_drift")
    if not set(defaults) <= set(members):
        raise ValueError("rust_project_cargo_v3_workspace_defaults_drift")
    lines = ["[workspace]", 'resolver = "2"']
    lines.extend(_array("members", members))
    lines.extend(_array("default-members", defaults))
    lines.extend([
        "", "[workspace.metadata.c2rust]",
        f'workspace_id = {_toml_string(workspace["workspace_id"])}',
        f'rust_project_ir_sha256 = "{ir_sha256}"',
        f'projection_sha256 = "{projection_sha256}"',
    ])
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_package_toml(
    package: Mapping[str, Any], targets: Sequence[Mapping[str, Any]],
    packages: Mapping[str, Mapping[str, Any]], edition: str,
) -> bytes:
    name = _cargo_name(package.get("name"), "package")
    if edition not in _EDITIONS:
        raise ValueError("rust_project_cargo_v3_edition_unrepresentable")
    roots = [target for target in targets if target["kind"] in {"lib", "cdylib"}]
    if len(roots) > 1:
        raise ValueError("rust_project_cargo_v3_library_target_unrepresentable")
    bin_names = [target["name"] for target in targets if target["kind"] == "bin"]
    if len(bin_names) != len(set(bin_names)):
        raise ValueError("rust_project_cargo_v3_target_name_collision")
    lines = [
        "[package]", f"name = {_toml_string(name)}", 'version = "0.0.0"',
        f"edition = {_toml_string(edition)}", "publish = false",
        "autolib = false", "autobins = false", "autoexamples = false",
        "autotests = false", "autobenches = false", "",
        "[package.metadata.c2rust]",
        f'package_id = {_toml_string(package["package_id"])}',
        f'build_ir_target_id = {_toml_string(package["build_ir_target_id"])}',
    ]
    for target in sorted(targets, key=_target_key):
        lines.extend(["", *_target_table(package, target)])
    dependencies = _dependencies(package, packages)
    if dependencies:
        lines.extend(["", "[dependencies]"])
        for alias, dependency, relative in dependencies:
            lines.append(
                f"{alias} = {{ package = {_toml_string(dependency['name'])}, "
                f"path = {_toml_string(relative)} }}"
            )
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_cargo_lock(
    packages: Sequence[Mapping[str, Any]],
) -> bytes:
    by_id = {str(package["package_id"]): package for package in packages}
    ordered = sorted(packages, key=lambda item: str(item["name"]))
    lines = [
        "# This file is automatically @generated by Cargo.",
        "# It is not intended for manual editing.", "version = 3",
    ]
    for package in ordered:
        lines.extend([
            "", "[[package]]", f"name = {_toml_string(package['name'])}",
            'version = "0.0.0"',
        ])
        dependencies = sorted(
            str(by_id[package_id]["name"])
            for package_id in package["dependency_package_ids"]
        )
        if dependencies:
            lines.extend(_array("dependencies", dependencies))
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_target_root(
    target: Mapping[str, Any], modules: Sequence[Mapping[str, Any]],
    dependency_aliases: Sequence[str] = (),
) -> bytes:
    entry_id = target["entry_module_id"]
    root_dir = posixpath.dirname(str(target["root_path"])) or "."
    lines = ["// @generated from RustProjectIR v3; do not edit.", ""]
    for alias in sorted(dependency_aliases):
        if not _RUST_IDENT.fullmatch(alias):
            raise ValueError("rust_project_cargo_v3_dependency_alias_collision")
        lines.extend([f"pub use {alias}::*;", ""])
    for module in modules:
        relative = posixpath.relpath(str(module["render_path"]), root_dir)
        if module["module_id"] == entry_id:
            lines.extend([f"include!({_rust_string(relative)});", ""])
            continue
        name = module_name(module)
        lines.extend([
            f"#[path = {_rust_string(relative)}]", f"mod {name};",
            f"pub use self::{name}::*;", "",
        ])
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def relative_inside(root: str, path: str) -> str:
    root_parts = PurePosixPath(root).parts
    path_parts = PurePosixPath(path).parts
    if path_parts[:len(root_parts)] != root_parts or len(path_parts) <= len(root_parts):
        raise ValueError("rust_project_cargo_v3_path_outside_package")
    return PurePosixPath(*path_parts[len(root_parts):]).as_posix()


def _target_table(
    package: Mapping[str, Any], target: Mapping[str, Any],
) -> list[str]:
    kind = target["kind"]
    name = _cargo_name(target.get("name"), "target")
    path = relative_inside(package_root(str(package["package_id"])), target["root_path"])
    crate_types = target["crate_types"]
    if kind == "bin":
        if crate_types != ["bin"]:
            raise ValueError("rust_project_cargo_v3_bin_crate_type_invalid")
        return [
            "[[bin]]", f"name = {_toml_string(name)}",
            f"path = {_toml_string(path)}", "test = false", "bench = false",
        ]
    if kind == "cdylib":
        if crate_types != ["cdylib"]:
            raise ValueError("rust_project_cargo_v3_cdylib_crate_type_invalid")
    elif kind == "lib":
        if not crate_types or len(crate_types) != len(set(crate_types)) or not set(
            crate_types
        ) <= _LIB_CRATE_TYPES:
            raise ValueError("rust_project_cargo_v3_lib_crate_type_invalid")
    else:
        raise ValueError("rust_project_cargo_v3_target_kind_unrepresentable")
    quoted = ", ".join(_toml_string(item) for item in crate_types)
    return [
        "[lib]", f"name = {_toml_string(name)}", f"path = {_toml_string(path)}",
        f"crate-type = [{quoted}]", "test = false", "doctest = false",
        "bench = false",
    ]


def _dependencies(
    package: Mapping[str, Any], packages: Mapping[str, Mapping[str, Any]],
) -> list[tuple[str, Mapping[str, Any], str]]:
    result = []
    aliases = set()
    current_root = package_root(str(package["package_id"]))
    for package_id in package["dependency_package_ids"]:
        dependency = packages[str(package_id)]
        alias = str(dependency["name"]).replace("-", "_")
        if not _RUST_IDENT.fullmatch(alias) or alias in aliases:
            raise ValueError("rust_project_cargo_v3_dependency_alias_collision")
        aliases.add(alias)
        relative = posixpath.relpath(
            package_root(str(dependency["package_id"])), current_root,
        )
        result.append((alias, dependency, relative))
    return sorted(result, key=lambda item: (item[0], str(item[1]["package_id"])))


def _cargo_name(value: Any, label: str) -> str:
    if not isinstance(value, str) or not _CARGO_NAME.fullmatch(value):
        raise ValueError(f"rust_project_cargo_v3_{label}_name_unrepresentable")
    return value


def _target_key(value: Mapping[str, Any]) -> tuple[int, str, str]:
    return (0 if value["kind"] in {"lib", "cdylib"} else 1,
            str(value["name"]), str(value["target_id"]))


def _array(name: str, values: Sequence[str]) -> list[str]:
    return [f"{name} = [", *(f"  {_toml_string(value)}," for value in values), "]"]


def _toml_string(value: Any) -> str:
    if not isinstance(value, str) or any(ord(char) < 32 for char in value):
        raise ValueError("rust_project_cargo_v3_toml_string_unrepresentable")
    return json.dumps(value, ensure_ascii=False)


def _rust_string(value: str) -> str:
    if "\\" in value or any(ord(char) < 32 for char in value):
        raise ValueError("rust_project_cargo_v3_rust_path_unrepresentable")
    return '"' + value.replace('"', '\\"') + '"'


__all__ = [
    "checked_output_path", "module_name", "package_root", "relative_inside",
    "render_cargo_lock", "render_package_toml", "render_target_root",
    "render_workspace_toml",
]
