from __future__ import annotations


PRIVATE_IMPORT_SPECS = (
    ("build_adapter", "make_build_ir_adapter", "MAKE_INPUT_KIND MakeReportSelection discover_make_project materialize_make_build_ir_stage"),
    ("build_ir_reopen", "make_build_ir_reopen", "accepted_make_provenance_role accepted_make_raw_roles reproject_bound_make_build_ir"),
    ("make_build_ir_adapter", "make_build_ir_closure_artifacts", "project_make_closure_artifacts"),
    ("make_build_ir_adapter", "make_build_ir_projection", "MAKE_RAW_ROLE normalize_make_translation_units project_make_build_ir"),
    ("make_build_ir_adapter", "make_dry_run_parser", "MAX_COMMANDS"),
    ("make_build_ir_adapter", "make_dry_run_report_io", "MAX_REPORT_BYTES reopen_make_dry_run_report verify_make_dry_run_report_inputs"),
    ("make_build_ir_closure", "make_build_ir_closure_resolution", "RESOLUTION_KIND assess_external_dependency_resolutions"),
    ("make_build_ir_projection", "make_build_ir_closure", "project_make_closure"),
    ("make_build_ir_projection", "make_build_ir_external", "project_make_external_dependencies"),
    ("make_build_ir_projection", "make_build_ir_toolchains", "abi_facts legacy_toolchain_id legacy_toolchains"),
    ("make_build_ir_projection", "make_dry_run_binding", "repository_path_argument"),
    ("make_build_ir_reopen", "make_build_ir_adapter", "reproject_make_build_ir"),
    ("make_build_ir_reopen", "make_build_ir_projection", "MAKE_RAW_ROLE"),
    ("make_dry_run_cli", "make_dry_run_collect", "collect_make_facts"),
    ("make_dry_run_collect", "make_dry_run_cas", "make_cas_reference write_make_cas"),
    ("make_dry_run_collect", "make_dry_run_collect_io", "make_command_input_refs persist_make_raw_outputs persist_make_static validate_make_collection_inputs"),
    ("make_dry_run_collect", "make_dry_run_contract", "MAX_STDERR_BYTES canonical_make_dry_run_report_bytes create_make_dry_run_report"),
    ("make_dry_run_collect", "make_dry_run_host_evidence", "canonical_make_host_preflight_bytes"),
    ("make_dry_run_collect", "make_dry_run_linux", "MakeDryRunBackendDiscovery canonical_make_toolchain_evidence_bytes discover_make_dry_run_backend"),
    ("make_dry_run_collect", "make_dry_run_parser", "MAX_STDOUT_BYTES parse_make_dry_run_stdout"),
    ("make_dry_run_collect", "make_dry_run_report_io", "MAX_REPORT_BYTES reopen_make_dry_run_report"),
    ("make_dry_run_collect", "make_dry_run_runner", "canonical_make_dry_run_plan_bytes create_make_dry_run_plan run_make_dry_run"),
    ("make_dry_run_collect", "make_dry_run_snapshot", "MAX_SNAPSHOT_MANIFEST_BYTES canonical_repository_snapshot_bytes capture_repository_snapshot snapshot_file_map verify_repository_snapshot"),
    ("make_dry_run_collect_io", "make_dry_run_binding", "normalize_repository_path validated_targets validated_working_directory"),
    ("make_dry_run_collect_io", "make_dry_run_cas", "validated_make_output_root write_make_cas"),
    ("make_dry_run_collect_io", "make_dry_run_contract", "MAX_STDERR_BYTES"),
    ("make_dry_run_collect_io", "make_dry_run_parser", "MAX_STDOUT_BYTES"),
    ("make_dry_run_contract", "make_dry_run_binding", "validated_working_directory"),
    ("make_dry_run_contract", "make_dry_run_contract_refs", "MakeDryRunContractError artifact_ref artifact_refs fail fixed_argv require_raw_cas_ref require_snapshot_cas_ref targets"),
    ("make_dry_run_contract", "make_dry_run_parser", "MAX_STDOUT_BYTES PARSER_NAME PARSER_VERSION parse_make_dry_run_stdout validate_make_dry_run_commands"),
    ("make_dry_run_contract", "make_dry_run_result", "MakeDryRunOutcome validate_successful_make_outcome"),
    ("make_dry_run_contract_refs", "make_dry_run_binding", "fixed_make_argv validated_targets"),
    ("make_dry_run_linux", "make_dry_run_host_evidence", "MAKE_REQUIRED_CAPABILITIES validate_make_host_preflight"),
    ("make_dry_run_linux", "make_dry_run_process", "run_make_bubblewrap_process"),
    ("make_dry_run_linux", "make_dry_run_result", "MakeDryRunExecution"),
    ("make_dry_run_linux", "make_dry_run_runner", "MakeDryRunPreflight validate_make_dry_run_plan"),
    ("make_dry_run_linux", "make_dry_run_sandbox", "build_make_bubblewrap_argv run_make_sandbox_preflight"),
    ("make_dry_run_linux", "make_dry_run_toolchain", "MAKE_TOOLCHAIN_KIND canonical_make_toolchain_evidence_bytes create_make_toolchain_evidence file_sha256 gnu_make_version trusted_executable valid_backend_version validate_make_toolchain_evidence"),
    ("make_dry_run_parser", "make_dry_run_binding", "normalize_repository_path validated_working_directory"),
    ("make_dry_run_parser", "make_dry_run_tools", "classify_make_tool"),
    ("make_dry_run_report_io", "make_dry_run_binding", "make_input_sha256"),
    ("make_dry_run_report_io", "make_dry_run_contract", "MAX_STDERR_BYTES canonical_make_dry_run_report_bytes validate_make_dry_run_report"),
    ("make_dry_run_report_io", "make_dry_run_host_evidence", "canonical_make_host_preflight_bytes validate_make_host_preflight"),
    ("make_dry_run_report_io", "make_dry_run_parser", "MAX_STDOUT_BYTES parse_make_dry_run_stdout"),
    ("make_dry_run_report_io", "make_dry_run_runner", "canonical_make_dry_run_plan_bytes validate_make_dry_run_plan"),
    ("make_dry_run_report_io", "make_dry_run_snapshot", "canonical_repository_snapshot_bytes verify_repository_snapshot"),
    ("make_dry_run_runner", "make_dry_run_binding", "fixed_make_argv make_input_sha256 validated_artifact_ref validated_working_directory"),
    ("make_dry_run_runner", "make_dry_run_contract", "MAX_STDERR_BYTES"),
    ("make_dry_run_runner", "make_dry_run_host_evidence", "MAKE_ENVIRONMENT MAKE_REQUIRED_CAPABILITIES MAKE_RESOURCE_LIMITS create_make_host_preflight validate_make_host_preflight"),
    ("make_dry_run_runner", "make_dry_run_parser", "MAX_STDOUT_BYTES"),
    ("make_dry_run_runner", "make_dry_run_result", "MakeDryRunExecution MakeDryRunOutcome"),
    ("make_dry_run_sandbox", "make_dry_run_binding", "validated_working_directory"),
    ("make_dry_run_sandbox", "make_dry_run_host_evidence", "MAKE_ENVIRONMENT"),
    ("make_dry_run_sandbox", "make_dry_run_process", "run_make_bubblewrap_process"),
    ("make_dry_run_snapshot", "make_dry_run_cas", "validated_make_output_root"),
    ("make_dry_run_snapshot", "make_dry_run_snapshot_io", "MAX_SNAPSHOT_FILES MAX_SNAPSHOT_FILE_BYTES MAX_SNAPSHOT_TOTAL_BYTES snapshot_repository_files"),
    ("make_dry_run_snapshot_io", "make_dry_run_cas", "validated_make_output_root"),
    ("make_dry_run_toolchain", "make_dry_run_host_evidence", "MAKE_ENVIRONMENT MAKE_RESOURCE_LIMITS"),
    ("project_migration_cli", "make_dry_run_cli", "add_collect_make_parser"),
)

ENTRYPOINT_PRIVATE_IMPORTS = {
    ("validation.tools.project_migration_harness", "make_dry_run_cli"):
        frozenset({"run_collect_make_command"}),
}


__all__ = ["ENTRYPOINT_PRIVATE_IMPORTS", "PRIVATE_IMPORT_SPECS"]
