from __future__ import annotations

import hashlib
import json
from pathlib import Path
import tempfile
import unittest
from typing import Any

from validation.tools._project_migration_harness.artifacts import content_sha256
from validation.tools._project_migration_harness.build_facts import (
    detect_build_system_facts, file_binding,
)
from validation.tools._project_migration_harness.project_test_inventory_meson_binding import (
    MAX_MESON_TEST_OUTPUT_BYTES, MESON_TEST_ADAPTER,
    capture_meson_test_build_binding,
)
from validation.tools._project_migration_harness.sandbox_contract import SandboxContract
from validation.tools._project_migration_harness.sandbox_requirements import (
    strict_sandbox_requirements,
)


class MesonInventoryTestCase(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory(prefix="meson-test-inventory-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name) / "source"
        self.build = self.root / "build"
        self.info = self.build / "meson-info"
        self.info.mkdir(parents=True)
        self.source = self.write("src/unit.c", b"int main(void) { return 0; }\n")
        self.manifest = self.write(
            "meson.build", b"project('neutral', 'c')\n",
        )
        self.binary = self.write("build/suite-bin", b"native-test-binary")
        self.fixture = self.write("fixture.txt", b"fixture")
        self.write(
            "build/build.ninja",
            b"# It is autogenerated by the Meson build system.\n",
        )
        self.database = self.write_json("build/compile_commands.json", [{
            "directory": str(self.build), "file": str(self.source),
            "arguments": [
                "cc", "-c", str(self.source), "-o",
                str(self.build / "suite-bin.p/unit.c.o"),
            ],
        }])
        self._write_meson_snapshot()
        self.tests = [self.direct_test()]
        self.write_tests(self.tests)
        database_binding = file_binding(self.root, self.database)
        self.discovery = {
            "build_system_facts": detect_build_system_facts(self.root),
            "compile_database": {
                "status": "bound", "selection": "explicit",
                **database_binding,
            },
        }
        binary_binding = {
            "path": "build/suite-bin", "kind": "file", "materialized": True,
            "sha256": hashlib.sha256(self.binary.read_bytes()).hexdigest(),
            "size_bytes": self.binary.stat().st_size,
        }
        self.build_ir = {
            "build_metadata": [{
                **database_binding, "kind": "file", "materialized": True,
            }],
            "translation_units": [],
            "targets": [{
                "target_id": "link-target", "kind": "link",
                "outputs": [binary_binding],
                "provenance": {
                    "raw_fact_role": "generated-build-closure",
                    "meson_target_id": "suite@exe",
                },
            }],
        }
        self.source_ref = {
            "path": "plan/project-test-meson-observation.json",
            "sha256": "d" * 64, "size_bytes": 10,
        }

    def write(self, relative: str, data: bytes) -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return path

    def write_json(self, relative: str, value: Any) -> Path:
        return self.write(
            relative,
            json.dumps(value, ensure_ascii=False, sort_keys=True).encode("utf-8"),
        )

    def write_tests(self, tests: list[Any]) -> None:
        self.write_json("build/meson-info/intro-tests.json", tests)

    def direct_test(self, **changes: Any) -> dict[str, Any]:
        value = {
            "cmd": [str(self.binary), str(self.fixture), "--strict"],
            "env": {"MODE": "portable"},
            "name": "source-suite", "workdir": str(self.build),
            "timeout": 30, "suite": ["neutral:unit"],
            "is_parallel": True, "priority": 0, "protocol": "exitcode",
            "depends": ["suite@exe"], "extra_paths": [],
        }
        value.update(changes)
        return value

    def observation(self, payload: list[Any] | None = None) -> dict[str, Any]:
        selected = self.tests if payload is None else payload
        binding, _ = capture_meson_test_build_binding(self.root, self.database)
        stdout = json.dumps(selected, sort_keys=True).encode("utf-8")
        tool = {"basename": "meson", "sha256": "a" * 64, "size_bytes": 1}
        launcher = {"basename": "bwrap", "sha256": "b" * 64, "size_bytes": 1}
        contract = SandboxContract(
            backend="bubblewrap-v1", launcher_sha256=launcher["sha256"],
            toolchain_sha256=tool["sha256"],
            requirements=strict_sandbox_requirements(
                cpu_seconds=30, address_space_bytes=1024 * 1024 * 1024,
                file_size_bytes=MAX_MESON_TEST_OUTPUT_BYTES,
                process_count=32, open_files=128,
            ),
        )
        value = {
            "schema_version": 1,
            "artifact_kind": "meson-introspect-tests-v1-observation",
            "adapter_version": MESON_TEST_ADAPTER,
            "command": ["meson", "introspect", "--tests", "build"],
            "build_directory": "build", "build_binding": binding,
            "tool": tool, "sandbox_launcher": launcher,
            "sandbox_contract": contract.payload(),
            "sandbox_contract_sha256": contract.sha256,
            "timeout_seconds": 30, "returncode": 0,
            "stdout_sha256": hashlib.sha256(stdout).hexdigest(),
            "stdout_size_bytes": len(stdout),
            "stderr_sha256": hashlib.sha256(b"").hexdigest(),
            "stderr_size_bytes": 0, "payload": selected,
            "payload_sha256": content_sha256(selected),
            "tests_executed": False, "semantic_gate": False,
        }
        value["observation_sha256"] = content_sha256(value)
        return value

    def _write_meson_snapshot(self) -> None:
        information = {
            name: {"file": filename, "updated": True}
            for name, filename in {
                "targets": "intro-targets.json",
                "buildoptions": "intro-buildoptions.json",
                "dependencies": "intro-dependencies.json",
                "compilers": "intro-compilers.json",
                "buildsystem_files": "intro-buildsystem_files.json",
                "tests": "intro-tests.json",
            }.items()
        }
        self.write_json("build/meson-info/meson-info.json", {
            "error": False,
            "directories": {
                "source": str(self.root), "build": str(self.build),
                "info": str(self.info),
            },
            "introspection": {
                "version": {"major": 1, "minor": 0, "full": "1.0.0"},
                "information": information,
            },
        })
        self.write_json("build/meson-info/intro-targets.json", [{
            "id": "suite@exe", "name": "suite", "type": "executable",
            "defined_in": str(self.manifest), "filename": [str(self.binary)],
            "build_by_default": True, "installed": False, "depends": [],
            "dependencies": [], "extra_files": [], "subproject": None,
            "target_sources": [{
                "language": "c", "machine": "host", "compiler": ["cc"],
                "parameters": [], "sources": [str(self.source)],
                "generated_sources": [],
            }],
        }])
        self.write_json("build/meson-info/intro-buildoptions.json", [{
            "name": "backend", "type": "combo", "value": "ninja",
            "section": "core", "machine": "any", "choices": ["ninja"],
        }])
        self.write_json("build/meson-info/intro-dependencies.json", [])
        self.write_json("build/meson-info/intro-compilers.json", {
            "host": {"c": {
                "id": "gcc", "exelist": ["cc"], "linker_exelist": ["cc"],
                "file_suffixes": ["c"], "default_suffix": "c",
                "version": "1", "full_version": "cc 1", "linker_id": "ld",
            }},
            "build": {},
        })
        self.write_json(
            "build/meson-info/intro-buildsystem_files.json",
            [str(self.manifest)],
        )


__all__ = ["MesonInventoryTestCase"]
