from __future__ import annotations

import hashlib
import shutil
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from validation.tools._project_migration_harness import cargo_project
from validation.tools._project_migration_harness import integration
from validation.tools._project_migration_harness import integration_generation as generations
from validation.tools._project_migration_harness import integration_validation as validation


def reconstruct_cargo_project(
    migration_manifest: Mapping[str, Any],
    candidate_descriptors: Sequence[Mapping[str, Any]], candidate_root: Path,
    *, max_source_bytes: int = cargo_project.MAX_SOURCE_BYTES,
) -> cargo_project.CargoProjectPlan:
    candidates = validation.load_candidates(
        candidate_descriptors, candidate_root, max_source_bytes,
    )
    normalized = validation.normalize_manifest(migration_manifest)
    dependencies, order = cargo_project._migration_dag(normalized)
    cargo_project._validate_candidates(candidates, dependencies)
    accepted = {item.group_id: item for item in candidates if item.status == "accepted"}
    cargo_project._validate_accepted(accepted, dependencies, order)
    ordered = [accepted[group_id] for group_id in order if group_id in accepted]
    unsafe_policy = cargo_project._unsafe_policy(normalized.get("unsafe_policy"), ordered)
    return _render_project(dependencies, order, ordered, unsafe_policy)


def integrate_candidates(
    migration_manifest: Mapping[str, Any],
    candidate_descriptors: Sequence[Mapping[str, Any]],
    candidate_root: Path, project_root: Path,
    *, max_source_bytes: int = cargo_project.MAX_SOURCE_BYTES,
) -> dict[str, Any]:
    stage: Path | None = None
    previous_managed = False
    previous_preserved = True
    try:
        trusted_root = validation.trusted_root(candidate_root)
        target = validation.project_target(project_root, trusted_root)
        current = generations.recover_current_generation(target)
        previous_state, previous_managed = validation.existing_state(current or target)
        plan = reconstruct_cargo_project(
            migration_manifest, candidate_descriptors, trusted_root,
            max_source_bytes=max_source_bytes,
        )
        stage = generations.create_generation_stage(target)
        integration._write_stage(stage, plan.files)
        staged_state, staged_managed = validation.existing_state(stage)
        if not staged_managed or staged_state == "absent":
            raise cargo_project.ProjectInputError("staged_project_invalid", "atomic_write")
        generation = generations.publish_generation(stage, target, previous_state)
        stage = None
        manifest_bytes = plan.files[cargo_project.LAST_GOOD_MANIFEST]
        return {
            "schema_version": 1, "status": "integrated",
            "integrated_group_ids": list(plan.accepted_group_ids),
            "last_good_manifest": {"path": cargo_project.LAST_GOOD_MANIFEST,
                                   "sha256": validation.digest(manifest_bytes)},
            "unsafe_policy": plan.last_good_manifest["unsafe_policy"],
            "last_good_updated": True,
            "generation": {"id": generation.name, "current_pointer": generations.CURRENT,
                           "immutable": True},
            "cargo_executed": False, "diagnostics": [],
        }
    except cargo_project.ProjectInputError as error:
        return _failure(error.code, error.stage, error.group_id,
                        previous_managed, previous_preserved)
    except generations.GenerationCommitError as error:
        return _failure(error.code, "generation_publish", None,
                        previous_managed, error.preserved)
    except OSError:
        return _failure("integration_io_failure", "filesystem", None,
                        previous_managed, previous_preserved)
    finally:
        if stage is not None and stage.exists():
            shutil.rmtree(stage, ignore_errors=True)


def _render_project(
    dependencies: Mapping[str, tuple[str, ...]], order: Sequence[str],
    candidates: Sequence[cargo_project.CandidateSource], unsafe_policy: Mapping[str, Any],
) -> cargo_project.CargoProjectPlan:
    cargo = ('[package]\nname = "migrated-project"\nversion = "0.0.0"\n'
             'edition = "2021"\npublish = false\n\n[lib]\npath = "src/lib.rs"\n'
             '\n[features]\ndefault = []\n').encode("ascii")
    lock = ("# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\nversion = 3\n\n"
            "[[package]]\nname = \"migrated-project\"\nversion = \"0.0.0\"\n").encode("ascii")
    files = {"Cargo.toml": cargo, "Cargo.lock": lock}
    lines = ["// Legacy test fixture generated from a validated DAG.", ""]
    groups = []
    for candidate in candidates:
        path = f"src/{candidate.module_name}.rs"
        files[path] = candidate.source
        lines.append(f"mod {candidate.module_name};")
        if candidate.public_symbols:
            lines.append(f"pub use self::{candidate.module_name}::{{{', '.join(candidate.public_symbols)}}};")
        lines.append("")
        groups.append({
            "group_id": candidate.group_id, "module_name": candidate.module_name,
            "dependencies": list(dependencies[candidate.group_id]),
            "source": {"path": candidate.source_path, "sha256": candidate.sha256,
                       "size_bytes": len(candidate.source)},
            "public_symbols": list(candidate.public_symbols),
            "required_symbols": list(candidate.required_symbols),
            "unsafe_count": candidate.unsafe_count,
        })
    files["src/lib.rs"] = ("\n".join(lines).rstrip() + "\n").encode("ascii")
    refs = [{"path": path, "sha256": hashlib.sha256(data).hexdigest(),
             "size_bytes": len(data)} for path, data in sorted(files.items())]
    dag = {"dependencies": {key: list(dependencies[key]) for key in sorted(dependencies)},
           "order": list(order)}
    manifest = {
        "schema_version": 1, "generator": "deterministic-cargo-reconstruction-v1",
        "dag_sha256": hashlib.sha256(cargo_project.canonical_json_bytes(dag)).hexdigest(),
        "accepted_groups": groups, "unsafe_policy": dict(unsafe_policy),
        "cargo_executed": False, "files": refs,
    }
    files[cargo_project.LAST_GOOD_MANIFEST] = cargo_project.canonical_json_bytes(manifest)
    return cargo_project.CargoProjectPlan(files=files, last_good_manifest=manifest)


def _failure(
    code: str, stage: str, group_id: str | None,
    previous_managed: bool, previous_preserved: bool,
) -> dict[str, Any]:
    diagnostic = {"code": code[:96], "stage": stage[:48]}
    if isinstance(group_id, str) and group_id:
        diagnostic["group_id"] = group_id[:128]
    return {"schema_version": 1, "status": "failed", "integrated_group_ids": [],
            "last_good_preserved": previous_managed and previous_preserved,
            "cargo_executed": False, "diagnostics": [diagnostic]}


__all__ = ["integrate_candidates", "reconstruct_cargo_project"]
