from __future__ import annotations

import json
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from validation.tools._project_migration_harness import meson_paths
from validation.tools._project_migration_harness.discovery import discover_project
from validation.tools._project_migration_harness.generated_build_facts import (
    detect_generated_build_facts,
)
from validation.tools._project_migration_harness.generated_closure import (
    verify_generated_build_closure,
)
from validation.tools._project_migration_harness.meson_introspection import (
    inspect_meson_introspection, verify_meson_introspection,
)


class MesonIntrospectionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="meson-facts-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name) / "source"
        self.root.mkdir()

    def write(self, relative: str, value: str | bytes) -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(value) if isinstance(value, bytes) else path.write_text(
            value, encoding="utf-8"
        )
        return path

    def write_json(self, relative: str, value: object) -> Path:
        return self.write(relative, json.dumps(value, ensure_ascii=False))

    def project(self, *, materialized: bool = False) -> Path:
        source = self.write("src/unit.c", "int main(void) { return 0; }\n")
        extra = self.write("include/unit.h", "int unit(void);\n")
        defined = self.write("meson.build", "project('sample', 'c')\n")
        option_file = self.write("meson.options", "option('feature', type: 'boolean')\n")
        build = self.root / "build"
        self.write(
            "build/build.ninja",
            "# It is autogenerated by the Meson build system.\n"
            "rule c_LINKER\n  command = clang $in -o $out\n"
            "build program: c_LINKER unit.o\n",
        )
        database = self.write_json("build/compile_commands.json", [{
            "directory": str(self.root), "file": "src/unit.c",
            "arguments": ["clang", "-c", "src/unit.c", "-o", "build/unit.o"],
            "output": "build/unit.o",
        }])
        if materialized:
            self.write("build/generated.c", "int generated(void) { return 1; }\n")
            self.write("build/program", b"program-v1")
            self.write("build/unit.o", b"object-v1")
        info_root = build / "meson-info"
        information = {
            name: {"file": filename, "updated": True}
            for name, filename in {
                "targets": "intro-targets.json",
                "buildoptions": "intro-buildoptions.json",
                "dependencies": "intro-dependencies.json",
                "compilers": "intro-compilers.json",
                "buildsystem_files": "intro-buildsystem_files.json",
            }.items()
        }
        self.write_json("build/meson-info/meson-info.json", {
            "error": False,
            "directories": {
                "source": str(self.root), "build": str(build), "info": str(info_root),
            },
            "introspection": {
                "version": {"major": 1, "minor": 0, "full": "1.0.0"},
                "information": information,
            },
        })
        targets = [
            self.target("generator@cus", "generator", "custom", defined,
                        [build / "generated.c"]),
            self.target("sample@exe", "sample", "executable", defined,
                        [build / "program"], depends=["generator@cus"],
                        dependencies=["sample-dependency"], extra_files=[extra],
                        sources=[source], generated=[build / "generated.c"]),
            self.target("helper@run", "helper", "run", defined, []),
            self.target("archive@sta", "archive", "static library", defined,
                        [build / "libarchive.a"]),
            self.target("shared@sha", "shared", "shared library", defined,
                        [build / "libshared.so"]),
            self.target("module@sha", "module", "shared module", defined,
                        [build / "module.so"]),
            self.target("java@jar", "java", "jar", defined, [build / "java.jar"]),
        ]
        self.write_json("build/meson-info/intro-targets.json", targets)
        self.write_json("build/meson-info/intro-buildoptions.json", [
            self.option("backend", "combo", "ninja", choices=["ninja"]),
            self.option("api-token", "string", "option-secret"),
        ])
        self.write_json("build/meson-info/intro-dependencies.json", [{
            "name": "sample-dependency", "type": "pkgconfig", "version": "1.0",
            "compile_args": ["-DDEPENDENCY_SECRET=do-not-expose"],
            "link_args": ["-lsample"], "depends": ["generator@cus"],
            "dependencies": ["nested-external"],
        }])
        self.write_json("build/meson-info/intro-compilers.json", {
            "host": {"c": {
                "id": "clang", "exelist": ["/secret/toolchain/clang"],
                "linker_exelist": ["/secret/toolchain/ld"],
                "file_suffixes": ["c"], "default_suffix": "c", "version": "18.0",
                "full_version": "clang 18.0", "linker_id": "ld.lld",
            }},
            "build": {},
        })
        self.write_json(
            "build/meson-info/intro-buildsystem_files.json",
            [str(defined), str(option_file)],
        )
        return database

    @staticmethod
    def option(name: str, kind: str, value: object, **extra: object) -> dict[str, object]:
        return {
            "name": name, "type": kind, "value": value, "section": "core",
            "machine": "any", **extra,
        }

    @staticmethod
    def target(
        identifier: str, name: str, kind: str, defined: Path, outputs: list[Path],
        *, depends: list[str] | None = None, dependencies: list[str] | None = None,
        extra_files: list[Path] | None = None, sources: list[Path] | None = None,
        generated: list[Path] | None = None,
    ) -> dict[str, object]:
        groups = []
        if sources or generated:
            groups.append({
                "language": "c", "machine": "host", "compiler": ["clang"],
                "parameters": ["-DMESON_TARGET_SECRET=do-not-expose"],
                "sources": [str(path) for path in sources or []],
                "generated_sources": [str(path) for path in generated or []],
            })
        return {
            "id": identifier, "name": name, "type": kind,
            "defined_in": str(defined), "filename": [str(path) for path in outputs],
            "build_by_default": kind != "run", "installed": False,
            "depends": depends or [], "dependencies": dependencies or [],
            "extra_files": [str(path) for path in extra_files or []],
            "target_sources": groups,
        }

    def report(self) -> dict[str, object]:
        return inspect_meson_introspection(
            self.root, self.root / "build/compile_commands.json"
        )

    def test_configure_only_ready_binds_inputs_and_declares_outputs(self) -> None:
        database = self.project()
        report = inspect_meson_introspection(self.root, database)

        self.assertEqual("ready", report["status"], report)
        self.assertEqual(7, len(report["snapshot_files"]))
        self.assertEqual(
            ["include/unit.h", "meson.build", "meson.options", "src/unit.c"],
            [item["path"] for item in report["referenced_artifacts"]],
        )
        targets = {item["id"]: item for item in report["targets"]}
        self.assertEqual(
            {"custom", "executable", "jar", "run", "shared library",
             "shared module", "static library"},
            {item["type"] for item in targets.values()},
        )
        self.assertFalse(targets["sample@exe"]["outputs"][0]["materialized"])
        generated = targets["sample@exe"]["source_groups"][0]["generated_sources"][0]
        self.assertEqual("generator@cus", generated["producer"]["target_id"])
        self.assertEqual("custom", generated["producer"]["target_type"])
        self.assertEqual(["generator@cus"], targets["sample@exe"]["target_dependency_ids"])
        self.assertEqual(
            ["sample-dependency"], targets["sample@exe"]["external_dependency_names"]
        )
        self.assertEqual(
            ["generator@cus"], report["dependencies"][0]["target_dependency_ids"]
        )
        encoded = json.dumps(report, ensure_ascii=False)
        for secret in ("do-not-expose", "option-secret", "/secret/toolchain"):
            self.assertNotIn(secret, encoded)
        self.assertEqual(
            "only_compile_database_parent_inspected",
            report["authority"]["build_root_selection"]["evidence_boundary"],
        )

    def test_materialized_outputs_are_stream_hash_bound(self) -> None:
        self.project(materialized=True)
        targets = {item["id"]: item for item in self.report()["targets"]}
        output = targets["sample@exe"]["outputs"][0]
        generated = targets["sample@exe"]["source_groups"][0]["generated_sources"][0]
        self.assertTrue(output["materialized"])
        self.assertEqual(64, len(output["sha256"]))
        self.assertTrue(generated["materialized"])

    def test_missing_metadata_and_metadata_drift_fail_closed(self) -> None:
        database = self.project()
        compilers = self.root / "build/meson-info/intro-compilers.json"
        compilers.unlink()
        self.assertIn("meson_compilers_missing", self.report()["blockers"])

        database = self.project()
        info_path = self.root / "build/meson-info/meson-info.json"
        info = json.loads(info_path.read_text(encoding="utf-8"))
        info["introspection"]["information"].pop("buildsystem_files")
        info_path.write_text(json.dumps(info), encoding="utf-8")
        self.assertIn(
            "meson_buildsystem_files_information_mismatch", self.report()["blockers"]
        )

        database = self.project()
        expected = inspect_meson_introspection(self.root, database)
        compilers = self.root / "build/meson-info/intro-compilers.json"
        metadata = json.loads(compilers.read_text(encoding="utf-8"))
        metadata["host"]["c"]["version"] = "18.1"
        compilers.write_text(json.dumps(metadata), encoding="utf-8")
        self.assertEqual(
            [{"kind": "meson_snapshot_drift"}],
            verify_meson_introspection(self.root, database, expected),
        )

    def test_declared_output_materialization_is_detected_as_drift(self) -> None:
        database = self.project()
        expected = inspect_meson_introspection(self.root, database)
        self.write("build/program", b"program-v2")
        self.assertEqual(
            [{"kind": "meson_snapshot_drift"}],
            verify_meson_introspection(self.root, database, expected),
        )

    def test_ordinary_ninja_with_coincidental_directories_is_not_meson(self) -> None:
        database = self.write_json("build/compile_commands.json", [])
        self.write("build/build.ninja", "rule cc\n  command = cc\n")
        (self.root / "build/meson-private").mkdir()
        (self.root / "build/meson-info").mkdir()
        report = inspect_meson_introspection(self.root, database)
        self.assertEqual("not_detected", report["status"])
        self.assertEqual([], report["blockers"])
        self.assertEqual([], detect_generated_build_facts(self.root, database)["blockers"])

    def test_schema_and_reparse_fail_closed(self) -> None:
        self.project()
        targets_path = self.root / "build/meson-info/intro-targets.json"
        targets = json.loads(targets_path.read_text(encoding="utf-8"))
        targets.append(dict(targets[0]))
        targets_path.write_text(json.dumps(targets), encoding="utf-8")
        self.assertIn("meson_target_id_duplicate", self.report()["blockers"])

        self.project()
        dependency = self.root / "build/meson-info/intro-dependencies.json"
        original = meson_paths._is_reparse
        with mock.patch.object(
            meson_paths, "_is_reparse",
            side_effect=lambda path: path.resolve() == dependency.resolve() or original(path),
        ):
            self.assertIn("meson_reparse_path", self.report()["blockers"])

    def test_generated_closure_recomputes_meson_snapshot_drift(self) -> None:
        database = self.project(materialized=True)
        closure = discover_project(
            self.root, compile_database=database
        )["generated_build_closure"]
        self.assertEqual("ready", closure["status"], closure)
        self.write_json("build/meson-info/intro-dependencies.json", [])
        verified = verify_generated_build_closure(self.root, closure)
        self.assertEqual("blocked", verified["status"])
        kinds = {item["kind"] for item in verified["blockers"]}
        self.assertIn("meson_snapshot_drift", kinds)
        self.assertIn("artifact_sha256_drift", kinds)


if __name__ == "__main__":
    unittest.main()
